language: elixir
elixir:
  - 1.6.0
otp_release:
  - 20.2
sudo: false
addons:
  postgresql: '9.4'
notifications:
  email: false
env:
  - MIX_ENV=test DATABASE_URL="postgres://localhost:5432/giphy_test"
before_script:
  - mix ecto.create
